<?php
/**
 * Moogento
 *
 * SOFTWARE LICENSE
 *
 * This source file is covered by the Moogento End User License Agreement
 * that is bundled with this extension in the file License.html
 * It is also available online here:
 * https://moogento.com/License.html
 *
 * NOTICE
 *
 * If you customize this file please remember that it will be overwritten
 * with any future upgrade installs.
 * If you'd like to add a feature which is not in this software, get in touch
 * at moogento.com for a quote.
 *
 * ID          pe+sMEDTrtCzNq3pehW9DJ0lnYtgqva4i4Z=
 * File        backorders.phtml
 * @category   Moogento
 * @package    pickPack
 * @copyright  Copyright (c) 2014 Moogento <info@moogento.com> / All rights reserved.
 * @license    https://moogento.com/License.html
 */
?>
<?php $_order = $this->getOrder(); ?>
<div class="inputs_for_admin_weight">
    <input class="text_for_admin_weight"
           value="<?php echo $_order->getSzy_weight(); ?>"
           data-value="<?php echo $_order->getSzy_weight(); ?>"
           data-changeurl="<?php echo $this->getUrl('*/sales_order_process/orderWeightEditFromGrid') ?>"
           data-orderid="<?php echo $_order->getId() ?>"
    />
    <button title="Submit" type="button" class="submit_for_admin_weight">
        <span><?php echo Mage::helper('moogento_shipeasy')->__('Submit'); ?></span>
    </button>
    <button title="Cancel" type="button" class="cancel_for_admin_weight">
        <span><?php echo Mage::helper('moogento_shipeasy')->__('Cancel'); ?></span>
    </button>
</div>
<div>
    <?php
        echo $_order->getSzy_weight();
    ?>
</div>
<span class="edit-icon"></span>
